name: BUILD AND TEST
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Install Docker Compose 
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy .env.sample to .env
        run: cp .env.sample .env
      
      - name: Run migration
        run: docker compose run --rm app sh -c "alembic upgrade head"

      - name: Test
        run: docker compose run --rm app sh -c "pytest"
      
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
