name: BUILD AND TEST
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: github_actions_db
          POSTGRES_TEST_DB: test_github_actions_db
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        id: dependency
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir psycopg2-binary
          pip install --no-cache-dir -r requirements.txt
          pip install flake8

      - name: Flake8 Lint
        run: |
          flake8
        id: flake8

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: flake8-lint-results
      #     path: |
      #       ./
      #       *.py
      #   if: always()

      - name: Run migration
        run: alembic upgrade head
      
      - name: Test with pytest
        run: pytest
